### PR TITLE
Bootstrap dependencies at run-time.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Review by hobinjk — COMMENTED** [review]
Isn't this why we have addon-builder?

**Comment by mrstegeman** [comment]
Yes, but this defeats the need for it. Seems easier to just have one package, where we can, than one for every possible platform.

**Comment by dhylands** [comment]
I think that this will work for modules which have simple native code, but it won't know how to download and install external C dependencies. It also means that we need a toolchain on the device. This is currently the case for Raspbian, but not for OpenWRT.

**Comment by hobinjk** [comment]
I think prebuilding is very important for performance, reliability, and future-proofing. It takes my 3B pi 40-60 seconds to run `npm install --production` for this adapter. In contrast, it takes less than 2 seconds to download and unpack the bundled lg-tv-adapter. From a reliability standpoint, the npm install also requires the success of 156 independent downloads from npmjs.org. While running the install, npm uses around 1.25/4 cores. Its memory usage is much nicer, peaking at ~70 MB, but I don't think that we'll be able to run `npm install` on single core/limited memory devices.

I think it's better to focus around automating the flow of moving from an addon-builder build result to an addon-list PR.

(this also applies to the pip invocations being done in bootstrap.py by the mysensors adapter but I thought that was necessary for some fancy specific setup)

**Comment by dhylands** [comment]
I've already mostly automated the process of going from the addon-builder to the addon-list.

After running the addon-builder, you can run the update.py script from the addon-list repository. Something like:
```
./update.py zigbee-adapte 0.7.3
```
and it will update the relevent sections of the addon-list using the files created by the addon-builder.

**Comment by mrstegeman** [comment]
My main motivation was that when we switch to generic OpenWrt, the number of architectures we may need to support could explode. This provided an easy way around that.

If we want to go all-in in binary packages, that’s fine, but we’ll need to change about 75% of the Python add-ons, as this is what they do.

**Pull request closed without merging**
